### ISSUE TITLE
Problem Uncaught TypeError: Cannot read property 'appendChild' of undefined

### ISSUE THREAD

**Issue by Barzon** [matthojo/videojs-Background#10]
I can't init the script, error on line 61 in vjs Background.
I put script and code at the end and header, but doesn't work.

Same error.

**Comment by matthojo** [comment]
Hello, do you have you video element setup like the example https://github.com/matthojo/videojs-Background/blob/master/example.html#L42-L48 ?

Are you also calling your video script in your head or via onLoad? Moving your script tag to the end of your page, or add an onLoad handler so it fires after the page has loaded.

**Comment by snakefooc** [comment]
I have same error for change the container element i need use class

**Comment by Barzon** [comment]
I tested various sets of template and css, the correct way is after video tag put the scripts with js.

Thanks!
