### ISSUE TITLE
Mobile issues

### ISSUE THREAD

**Issue by nppsbh** [matthojo/videojs-Background#12]
Hi.
I am using your Background plugin with Youtube and Vimeo plugins.
On desktop devices i manage to get all working together, but with mobile devices i am struggling with some issues. 
I could only test with Android with native and chrome browsers.
If i don't use your plugin all video types are working in both browsers, obviously not in full screen :). With your plugin, i only get it working with chrome with mp4 and Vimeo videos, but not with Youtube. With the native Android browser only partially mp4 worked, i say partially because it worked but not in full screen.
Can you please give me some guidance?

**Comment by matthojo** [comment]
Videos cannot autoplay on mobile, so the `poster` image is used instead.
