### ISSUE TITLE
import 'videojs-background';

### ISSUE THREAD

**Issue by IJsLauw** [matthojo/videojs-Background#17]
I'd like you use your lib in my (browserify) project I tried adding this (http://ifandelse.com/its-not-hard-making-your-library-support-amd-and-commonjs/) to your project, but this is all still new to me and I can't get it to work...

Would you mind having a stab at it?

**Comment by truetone** [comment]
I have a patched fork. You could run `npm install git://github.com/truetone/videojs-Background.git#npm-fix --save` until my pull request is merged here.
