### ISSUE TITLE
Window width vs element width

### ISSUE THREAD

**Issue by niallobrien** [matthojo/videojs-Background#2]
There's an issue with lines 89 & 90 that relates to iOS. As the calculations are based off the window dimensions, this is not always ideal as when you scroll down on iOS, the Mobile Safari url bar shrinks in height, which affects the window dimensions, thus causing the image to adjust accordingly.

Simply removing the conditionals on those two lines resolves the issue, however I'm not sure how this may affect usage of this plugin under other circumstances for others.

```
var containerW = settings.container.clientWidth,
  containerH = settings.container.clientHeight,
```

**Comment by niallobrien** [comment]
@matthojo Any thoughts on the above, or should I close this issue for now? Thanks.

**Comment by matthojo** [comment]
@niallobrien We could close for now, thank you. I've not touched this project is too long! It probably needs a fairly decent refactor.
