### ISSUE TITLE
Does not display background <div> in Fullscreen mode (see jsbin example)

### ISSUE THREAD

**Issue by videojs-user** [matthojo/videojs-Background#20]
[http://jsbin.com/vigatep/edit?html,output](url)

Should it work in Fullscreen mode, if not, can you explain why not?

**Comment by videojs-user** [comment]
In case relevant: Using chomium version 50.0.2661.102 Ubuntu 16.04

**Comment by matthojo** [comment]
Hello,

I cannot seem to replicate these results on my Mac using latest Chrome. By Fullscreen are you referring to http://output.jsbin.com/vigatep or native fullscreen?

**Comment by videojs-user** [comment]
Hi,
Can you run the code outside of jsbin and click the control bar Fullscreen icon. Can you still see the white square?

**Comment by videojs-user** [comment]
Just checked latest Firefox 46.0.1 for ubuntu 16.4 and same result - no white square displayed.

**Comment by matthojo** [comment]
Does this only happen for you on fullscreen? Do you have any styles for video.js (not just this plugin) that makes video z-index higher when fullscreen?

**Comment by videojs-user** [comment]
Yes, only fails in videojs initiated Fullscreen mode. Works correctly in F11 key initiated fullscreen.

No extra styles, all code is shown in .HTML file and is identical to your original plugin code.

**Comment by videojs-user** [comment]
Can you run the .HTML file as is and confirm you can still see the white square in native (videojs initiated) Fullscreen mode when using Mac?

**Comment by matthojo** [comment]
Sorry I understand the issue now, the white div is not overlaying over the top of the video because you are using the videos native 'fullscreen' button. The browser then makes the video fullscreen and overlays on top of everything - just like a normal video fullscreen.

**Comment by videojs-user** [comment]
Good, so, should your plugin show the white div or not in this Fullscreen mode - in your opinion?

**Comment by matthojo** [comment]
Not, as this is for a background element of a page rather than to override the native fullscreen display of video.

**Comment by videojs-user** [comment]
OK.... So in what way is the videojs control bar (<div>) different to this background white square (<div>), since the control bar is obviously still visible in Fullscreen mode?  Should they not be treated the same way within videojs? After all, they are both just Components within the videojs hierarchy. 

Is this a logical argument or am I misunderstanding  something about the composition of videojs?

**Comment by videojs-user** [comment]
Could you raise this point with videojs guys, please.
