### ISSUE TITLE
The element or ID supplied is not valid

### ISSUE THREAD

**Issue by nppsbh** [matthojo/videojs-Background#7]
Hi.
I could not get it working. I am getting this error 'The element or ID supplied is not valid. (videojs)'.
Calling 'videojs('bg-video').Background();'.
Can you help me on this?
Thanks.
video.js 4.12.11

**Comment by matthojo** [comment]
Hello, do you have you video element setup like the example https://github.com/matthojo/videojs-Background/blob/master/example.html#L42-L48 ?

Are you also calling your video script in your `head` or via `onLoad`? Moving your script tag to the end of your page, or add an `onLoad` handler so it fires after the page has loaded.

**Comment by nppsbh** [comment]
Thank you for your quick answer.
I made a test with your full example and it is working very well, i must say. I test it also with youtube.js plugin. Definitely it is something wrong on my side.
Thanks.

**Comment by matthojo** [comment]
No problem, are you able to post up what you currently have on CodePen / jsFiddle or somewhere? I could maybe help you solve your issue :)

**Comment by nppsbh** [comment]
I was calling video.js, youtube.js and videojs-background.js in the 'head' element, moving to the end of page start working without any issues. Thanks a lot for your help.
If you could give me your opinion about video.js i really appreciate. It is off topic, but here it is.
I am using video.js script to load a simple video as background, without controls, very simple thing.
My question is, should i remove in video.js script all unnecessary calls to make it lighter, or, in your opinion, it is not necessary?
Once again thank you for your support.

**Comment by matthojo** [comment]
The only issue with removing components of the library, is if you update the library you will have to re-remove all the bits you don't need.

Excluding the above, I don't foresee any issues from cropping up if you only remove the components you don't need, and that the components you remove are not referenced or used elsewhere.
